security: imx8m: general fixes
foundriesio/lmp-tools pull request #16
Opened 2021-08-17 18:23 UTC by vanmaegima

Using SDPU command makes the imx8mmevk board hang, so fix it to use SDPV commands.
Also emmc device for this board is at mmc dev 2, so use this as default on gen_close.uuu.

2021-08-17 19:46 UTC, MrCry0 requested changes

2021-08-17 19:46 UTC, MrCry0 commented on security/imx8m/gen_close.sh
>  SDPU: delay 1000
Can we use the SDPV protocol for the whole of this part?

2021-08-17 19:46 UTC, MrCry0 commented on security/imx8m/gen_fuse.sh
>  SDPU: delay 1000
ditto.

2021-08-17 19:46 UTC, MrCry0 commented on security/imx8m/gen_close.sh
> +SDPV: jump
Good catch!

2021-08-17 19:56 UTC, vanmaegima commented
Thanks for the review @MrCry0 , I addressed your comments!

2021-08-17 20:01 UTC, MrCry0 approved these changes

2021-08-17 20:02 UTC, MrCry0 approved these changes
LGTM, tested.

2021-08-17 22:32 UTC, Tim-Anderson approved these changes
LGTM

2021-08-18 01:18 UTC, mike-scott approved these changes

2021-08-18 01:18 UTC, merged